package:
  name: cypico
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - cython >=0.23
    - msinttypes r26  # [win]

  run:
    - python
    - numpy >=1.10

test:
  requires:
    - pillow

  imports:
    - cypico

about:
  home: https://github.com/menpo/cypico/
  license: BSD
